# -*- coding: utf-8 -*-
"""Lexicon-Based Sentiment Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EjHGSU0BhCQRUG9P2rs76V0mqItWeU0X
"""

import textblob as txb
import pandas as pd

df = pd.DataFrame(["I am very happy today.", "I feel sad.", "I do not like this product.", "The product is good but delivery system is very poor.", "I like to eat pizza."])
#df.head()

df['scores'] = df[0].apply(lambda x: txb.TextBlob(x).sentiment.polarity)
#df.head()

def map_scores(scores):
  if scores > 0.0:
    return 'positive'
  else:
    return 'negative'

df["Labels"] = df["scores"].apply(lambda x: map_scores(x))
#df.head()

d = {'positive': 1, 'negative': 0}
df["Labels"] = df["Labels"].map(d)
print(df.head())